### ISSUE TITLE
Fast sync doesn't seem to work with the latest node version

### ISSUE THREAD

**Issue by earthlingdavey** [lephleg/nano-node-docker#11]
It seems like the downloaded database from fast sync is moved to the wrong folder location.

I'm left with the following folder structure. It looks like I have a copy of the database in /RaiBlocks that isn't used.

    root@docker-s-2vcpu-4gb-sgp1-01:~/nano-node-docker/nano-node/Nano# du -h
    8.0K	./backup
    102M	./log
    16G	./RaiBlocks
    57G	.
    root@docker-s-2vcpu-4gb-sgp1-01:~/nano-node-docker/nano-node/Nano# ls -lh
    total 42G
    drwx------ 2 root root 4.0K Sep 26 13:17 RaiBlocks
    drwx------ 2 root root 4.0K Sep 26 13:27 backup
    -rw------- 1 root root  21G Sep 26 13:38 backup.vacuum.ldb
    -rw------- 1 root root 4.2K Sep 26 13:01 config.json
    -rw------- 1 root root  21G Sep 27 09:31 data.ldb
    -rw------- 1 root root 8.0K Sep 27 09:31 data.ldb-lock
    drwxr-xr-x 2 root root  20K Sep 27 09:31 log
    -rw-r--r-- 1 root root  31K Sep 27 09:31 nano-docker-output.log
    -rw------- 1 root root  285 Sep 26 13:01 rpc_config.json
    -rw------- 1 root root 964M Sep 27 06:29 vacuumed.ldb
    -rw------- 1 root root  44K Sep 26 13:33 wallets.ldb
    -rw------- 1 root root 8.0K Sep 27 09:31 wallets.ldb-lock
    root@docker-s-2vcpu-4gb-sgp1-01:~/nano-node-docker/nano-node/Nano# cd RaiBlocks/
    root@docker-s-2vcpu-4gb-sgp1-01:~/nano-node-docker/nano-node/Nano/RaiBlocks# ls -lh
    total 16G
    -rw------- 1 root root 16G Sep 26 10:04 data.ldb

At the moment my node is syncing from scratch. Which is fine with me. Please advise, should I delete /RaiBlocks ?

**Comment by lephleg** [comment]
Hey @daveybrown,

Yeah, it seems that the fast sync is still placing the downloaded files into the legacy directory instead of the new `/Nano` one. I will have to take a look at it in the following days. Thanks for letting me know.

For now, if you are happy with syncing from scratch, you can delete the `RaiBlocks/` without a problem.

**Comment by earthlingdavey** [comment]
Hey @lephleg, 

That's cool, I did have a look at your script, sorry, I'm a bash newbie and short on time otherwise I'd create a PR.

Thanks for such a quality project. 👍✌️

**Comment by amirmnsr** [comment]
I will only briefly mention the pull request #12 , which is not very big, but should still solve the problem.
