### ISSUE TITLE
Move to explicit version tags for Docker

### ISSUE THREAD

**Issue by zhyatt** [lephleg/nano-node-docker#14]
We are [moving to decommission use of the `latest` tag for the Docker images](https://github.com/nanocurrency/nano-node/issues/3182) as a best practice in favor of explicit version tags. Target is V22 for this change. This means watchtower will not be useful for the nano-node setup and with each version manual action by the node operator will be required. 

Although changes to this nano-node-docker setup may not be required, perhaps some cleanup and updates to the README or other areas where expectations of automatic node upgrading are set would be worthwhile to make it clearer that upgrades will require manual action going forward.

**Comment by lephleg** [comment]
Hello Zach! What about the `:latest` image tag? Are you going to fully deprecate it?

Nano Node Docker is mainly a development tool and I will make that clear in the documentation. Main net nodes, especially those with delegated amounts will always require special care and monitoring and shall not be left to be upgraded automatically.

**Comment by zhyatt** [comment]
👋 @lephleg - Yes, we are fully deprecating the use of `:latest` for production tags, see: https://github.com/nanocurrency/nano-node/pull/3183. Clarity in the documentation around development use only would be great and thanks for your awesome work on this and other things for Nano!

**Comment by lephleg** [comment]
Sure, not a problem! Thanks for letting me know. I will also remove the `:latest` tag as the default for the installer and require an explicit version for the node. Watchtower will still be useful for the rest of the components like the monitor and the proxy.

**Comment by lephleg** [comment]
Newly released [v4.4](https://github.com/lephleg/nano-node-docker/releases/tag/v4.4) implements the above considerations. Please advice any members of the community to upgrade if needed and let me know of any issues reported outside of this repository. Cheers! 🍻
