### ISSUE TITLE
Typo in file name for docker-compose.letsencypt.yml file

### ISSUE THREAD

**Issue by nanoble-org** [lephleg/nano-node-docker#2]
I was trying to automate some of the configuration for the file and noticed the filename has a typo.  Not sure if this is worth changing in case someone else has automated pieces here, but thought it was worth mentioning. Great work on this!

Current: docker-compose.letsencypt.yml

Suggested: docker-compose.letsencrypt.yml

**Comment by nanoble-org** [comment]
Also noticed that your documentation uses this command:

```docker-compose -f docker-compose.letsencrypt.yml up -d```

which will fail - so either the filename or documentation needs updating.

**Comment by lephleg** [comment]
Thanks for noticing @nanoble-org. I'm going to fix the filename as it is indeed mistyped.

**Comment by nanoble-org** [comment]
@lephleg Thanks for your work on this!  I have been actively working on automating a fast-bootstrapped node this morning and when I ran it a few moments ago it said it couldn't find ```docker-compose.letsencypt.yml``` - that's when I knew you were on top of things and fixed it!
