### ISSUE TITLE
How to upgrade node?

### ISSUE THREAD

**Issue by nullbio** [lephleg/nano-node-docker#3]
Thanks a lot for sharing and creating this. I have a quick question, is there an easy way to upgrade the node? Now that v15 is released, I'm still sitting on 14.2. There's a stress test tomorrow so I'm trying to get the new version in place before then. Appreciate some guidance here, thanks.

**Comment by nullbio** [comment]
Actually, I read it wrong. It's a stress test on the beta network I believe. Can you explain a bit about the upgrade process regardless? Thanks.

**Comment by lephleg** [comment]
Your node will get upgraded on its own by Watchtower, when v15 has been released by the Nano team and get marked with the `latest` tag on Docker hub.
