### ISSUE TITLE
Exposing rpc and modifying config.json

### ISSUE THREAD

**Issue by Outstep** [lephleg/nano-node-docker#5]
Hello,

I am working on setting up a NANO node and connecting to the Beta network so that I can test out some work. Actually, I am setting up a Canoe NANO server to talk to the Canoe NANO wallet and need to expose the RPC on the container to the host.

What is an easy way to do this with your scripts?

Also, I need to make a couple of modification to the

RaiBlocks/config.json

as well

any help would be useful :)

**Comment by lephleg** [comment]
You can expose the RPC port to the public by removing the localhost gateway restriction in the `docker-compose.yml` (or `docker-compose.letsencrypt.yml` if you're using Lets Encrypt) at line 14:

```
 - "127.0.0.1:55000:55000"
```

```
 - "55000:55000"
```

After the change you should re-run the installer with your latest settings:

```
sudo ./setup.sh $(cat settings)
```

The `config.json` is already mapped on your host inside `~/nano-node-docker/nano-beta-node/config.json`. You should stop your node before modifying this file and start it up again after you've applied your changes.

**Comment by Outstep** [comment]
Thanks for getting back to me and I will give this a try.

On a third question, I was just wondering if you would, by chance, know how
to configure things such that it would be a "private beta network" such
that I could generate my own genesis keys for a local setup which would not
call the NANO Beta or Real network?

Not sure if you know how to configure this but I would be interested in
this to work on a local copy on a private beta network setup.
Cheers and have a good night

**Comment by lephleg** [comment]
You'll probably have to fork Nano for that. In any case, this is out of the scope of this project. Better get in touch with the core team.

PS: Don't forget to leave a star if you found this installer helpful to you.
