### ISSUE TITLE
Add in alias for nano docker into ~/.bashrc

### ISSUE THREAD

**Issue by tmchow** [lephleg/nano-node-docker#7]
I suggest adding a line into ~/.bashrc for easier interaction with the nano node. 

`alias rai='sudo docker exec nano-node /usr/bin/rai_node'`

This allows you to run simpler commands like `rai --wallet_list` instead of the full docker command.

**Comment by lephleg** [comment]
I like it. This should be adjusted for the `nano-beta-node` container too.

**Comment by lephleg** [comment]
This has been finally added to [v4.0.](https://github.com/lephleg/nano-node-docker/releases/tag/v4.0)
